### ISSUE TITLE
Replay problems in Image Search

### ISSUE THREAD

**Issue by PedroG1515** [arquivo/pwa-technologies#1090]
The general issue that reflects replay errors related to the image search:

- [ ] Cdxj-indexer enconding problems #1091
- [ ] Problems adding the parameter collection #1093
- [ ] CDX indexes some collections are wrongly reporting content length 0 #912
- [ ] Apache not interpreting HTML encodings #439
- [ ] Replay imagens from IA collections #1094
- [ ] Exclude ".open" WARCs from Image and Page Indexing #1095
