### ISSUE TITLE
Track and log each clicked search result

### ISSUE THREAD

**Issue by igobranco** [arquivo/pwa-technologies#782]
## Description of the improvement 
To improve ours search rankings we need to log some information to be used latter to improve the rankings.

Information that we need to save: 
| information type | description |
| - | - |
| search criteria | each API GET contains all the search criteria |
| search results | the n results shown to the user. eg. for page search the ordered list of 10 pairs of timestamp-url. ` [{timestamp1:url1},{timestamp2:url2}, ....] ` |
| each search result link | has an internal redirect so we can track the position |

## Possible solution
Ideia from #700 . 
The link for each search result send to a tracking path that redirects to original wayback url.

### Generate search_id
The client generates an hash, md5, sha1 or similar based on API query + a now timestamp and send it has an additional attribute to the API URL, name it like search_id. The API doesn't need to process that search_id.
It needs to log the search url + the search results like ` [{timestamp1:url1},{timestamp2:url2}, ....] `. Preference on a single line, so it could be process more easily on the future. 

### Generate search result link
Each search result link shown to the user goes to a tracking URL that redirects to the original search result.

#### Like:
```
/page/view/<user_uid>_<search_id>_<position_on_search>/<timestamp>/<wayback_replay_url>
```
#### Where:

| parameter | parameter description |
| - | - |
| position | is the n position on the search result: eg: 1, 2, 3 ... | 
| user_uid | an hash generated on client side that identifies each user on subsequent searches. It has 1 day expire date |
| search_id | an hash of the search send by the client to the API to identify that unique search |
| timestamp | timestamp of the replayed wayback page |
| wayback_replay_url | the original page url |

that redirects to:
```
/wayback/<timestamp>/<wayback_replay_url>
```

## Image
For image search a similar approach is needed. But because the user doesn't need to go the archived page to view the image. We need to track an image view every time the user opens (clicks) an image.
```
/image/view/<user_uid>_<search_id>_<position_on_search>/<timestamp>/<wayback_replay_url>
```
Note: this path doesn't need to return a redirect to the image, because of how the image search screens are implemented. 

## Tasks:
- [x] generate a search_id and send it to search page API
- [x] generate a search_id and send it to search image API
- [x] create a new /page/view path to track each search page result click.
- [x] create a new /image/view path to track each search image result click.
- [ ] log requested url + search results on search page API @amourao 
- [ ] log requested url + search results on search image API @danielbicho 

## Future work possible analytics
Improve the search it self so we show the more relevant search result items on top.
Also a simple process on tracking requests could calculate the average and median of the position of the search result clicked.

**Comment by igobranco** [comment]
Created a separate tickets to log each requested API calls: #928 #929
